### ISSUE TITLE
CLI command to quickly see which languages work

### ISSUE THREAD

**Issue by seirl** [prologin/camisole#11]
> ###### Originally posted 2017-01-10 18:39 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

A bit like the /test endpoint but in CLI, and with a cleaner and colored output. The goal is for a human to check quickly which languages do work and see what fails and why.

**Comment by Zopieux** [comment]
> ###### Originally posted 2017-01-11 19:10 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

main: add 'languages' command to test working languages; fix #11


→ <<cset 5e3c99a2d7ed>>
