### ISSUE TITLE
Add a way to set arbitrary language names

### ISSUE THREAD

**Issue by seirl** [prologin/camisole#12]
> ###### Originally posted 2017-01-10 18:41 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Using `__class__.__name__` is a cool default but I think we should give more control to the user (like using a name descriptor that gives `__class__.__name__` when not set).

**Comment by Zopieux** [comment]
> ###### Originally posted 2017-01-11 20:38 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

What do you think of:

```python
class Python(Lang, name="my-python"):
    pass
```

**Comment by seirl** [comment]
> ###### Originally posted 2017-01-11 20:44 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

sgtm

**Comment by Zopieux** [comment]
> ###### Originally posted 2017-01-11 20:53 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

models: add name= kwarg on Lang; fix #12


→ <<cset 5e0aed803b42>>
