### ISSUE TITLE
Redesign the thing: use atomic "blocks" for compilers & runtimes, a Language is a sequence of blocks

### ISSUE THREAD

**Issue by Zopieux** [prologin/camisole#16]
> ###### Originally posted 2017-01-28 14:24 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

**Comment by seirl** [comment]
> ###### Originally posted 2017-03-26 18:11 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

models: add Program and use it for the languages (resolves #16)


→ <<cset 2e5e06e9031e>>
