### ISSUE TITLE
Add sanity checks around isolate calls to avoid box reuses

### ISSUE THREAD

**Issue by seirl** [prologin/camisole#17]
> ###### Originally posted 2017-02-13 20:30 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

**Comment by seirl** [comment]
> ###### Originally posted 2017-03-04 00:48 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

5d8828c should fix this but i'm keeping this open until we have proper tests.

**Comment by Zopieux** [comment]
310528e removes the lock.
