### ISSUE TITLE
Guess binaries paths from PATH instead of hardcoding them in the plugins

### ISSUE THREAD

**Issue by seirl** [prologin/camisole#18]
> ###### Originally posted 2017-02-13 20:31 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

**Comment by Zopieux** [comment]
> ###### Originally posted 2017-03-05 20:58 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Fixed in 979f9013c0f9
