### ISSUE TITLE
Actual documentation

### ISSUE THREAD

**Issue by Zopieux** [prologin/camisole#2]
> ###### Originally posted 2016-12-18 19:01 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

**Comment by seirl** [comment]
> ###### Originally posted 2017-01-10 18:00 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

readthedocs that contains:

* Quick installation via VM
* Installation for development
* Full documentation on the requests and the replies contents
* Page on security
* How to add a language

**Comment by Zopieux** [comment]
> ###### Originally posted 2017-01-12 01:02 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Drafted in 9a67e5e.

**Comment by Zopieux** [comment]
Mostly done in 74581c5.

**Comment by seirl** [comment]
If there are other specific things to add, we'll open new issues.
