### ISSUE TITLE
HTTPRequestEntityTooLarge: Request Entity Too Large

### ISSUE THREAD

**Issue by lastdreamer7591** [prologin/camisole#25]
Hi !

I'm using Camisole for a project, but I have a problem.

When I want to run a test with a huge entry (over than 1Mb), the exception "aiohttp.web_exceptions.HTTPRequestEntityTooLarge: Request Entity Too Large" is thrown.

Have you an idea how I can increase this size limit?

Thank you !

**Comment by Zopieux** [comment]
Hi there,

This is a known issue and a release fixing it will be done soon. In the meantime, as you can see in the tests, you can pass [an additional keyword](https://github.com/prologin/camisole/blob/49490d353eed932711244682737afc9d0729c765/tests/conftest.py#L58) to `make_application`.

**Comment by lastdreamer7591** [comment]
Thanks, it's ok now ;)

**Comment by Zopieux** [comment]
34949e757cdb201205dd9b025dedd5630dcab1ad lands this feature. Release will be there soon.
