### ISSUE TITLE
execve("/usr/bin/javac") : No such file or directory

### ISSUE THREAD

**Issue by lastdreamer7591** [prologin/camisole#27]
Hi,

I have a new problem.
Up to now, Camisole was set up on a personal Raspberry Pi with Archlinux in order to show the feasibility of using Camisole in a formal academical usage.

However, when I moved the configuration to the "real machine", a VM provided by the university with Debian 9 OS, Java stopped being supported.
When I try `camisole test -v`, I have the following error : 

    execve("/usr/bin/javac") : No such file or directory.

Of course, javac does exist in /usr/bin/ and does work adequately outside Camisole.

Any idea why Camisole can't find it?
Java is provided by the openjdk-8-jdk package (I'm not really proficient with Debian, so perhaps I'm missing something).

Thank you for you help,
Lastdreamer

**Comment by seirl** [comment]
Any chance you could come in our IRC channel? #prologin @ irc.freenode.net

It will be way easier to find the cause of the issue if we can talk there, i'll write a detailed explanation here.

**Comment by Zopieux** [comment]
Our CI build runs in Travis, which uses Debian images. You are getting this error because of the 
Debian *alternatives* system.

You need to define [an environment variable](https://github.com/prologin/camisole/blob/master/.travis.yml#L23) to pass through this mechanism.

**Comment by chen-robert** [comment]
@Zopieux Could you please elaborate on what you mean? I'm running into the same problem.

**Comment by seirl** [comment]
@chen-robert Hi, can you check whether `/usr/bin/java` is a symlink to something? If yes, which directory is it?

Usually, specifically for Java which uses the debian *alternatives* system, we need to mount other directories in /etc in which there are files that the symlinks in /usr/bin point to.

I thought we had that handled for Java here:

https://github.com/prologin/camisole/blob/master/camisole/languages/java.py#L41

So I'd be curious to know the path of your Java symlink. This line needs to be made more generic.

**Comment by chen-robert** [comment]
Hello @seirl! Sorry for the late reply.

`/usr/bin/java` is a symlink to `/etc/alternatives/java`.

**Comment by chen-robert** [comment]
Finally fixed the issue. I changed https://github.com/prologin/camisole/blob/7588b149cdb329b997c42e19deabd32b4f560cec/camisole/languages/java.py#L36 to `compiler = Program('/usr/lib/jvm/java-8-openjdk-amd64/bin/javac', opts=['-encoding', 'UTF-8'],`.

Maybe for future users, programmatically determine where the binaries are located?
