### ISSUE TITLE
Go support

### ISSUE THREAD

**Issue by Zopieux** [prologin/camisole#35]

**Comment by seirl** [comment]
The blocker was this issue https://github.com/golang/go/issues/20017 (thanks @multun :-) ). If there was a release of Go with that fixed, we can add it without too much trouble.

**Comment by multun** [comment]
We still have to wait a bit until the next release comes in => https://github.com/golang/go/wiki/Go-1.10-Release-Party

**Comment by seirl** [comment]
Fixed in dd3e2add58980d0001443ad0341222921618eb50
