### ISSUE TITLE
Support for the D Programming Language

### ISSUE THREAD

**Issue by andre2007** [prologin/camisole#36]
Please add support for the D Programming Language.
https://dlang.org/

**Comment by Zopieux** [comment]
dmd is [packaged](https://www.archlinux.org/packages/community/x86_64/dmd/) in the official Archlinux repositories, so it should be quite easy. Feel free to open a pull request if you have the time!

**Comment by andre2007** [comment]
Are there some instructions how to add a new language? Maybe a list of files to be added/changed would be great.

**Comment by Zopieux** [comment]
@andre2007 of course there is! Here: https://camisole.prologin.org/extending.html

**Comment by andre2007** [comment]
Please have a look at https://github.com/prologin/camisole/compare/master...andre2007:master

I am not sure about the travis file. Is it possible to use here the Archlinux repository as you mentioned?

The other way would be to use the official install script, as you can see in the travis file:
```curl https://dlang.org/install.sh | bash -s dmd```

Afterwards to use it, you can source it
```source $(~/dlang/install.sh dmd -a)```

**Comment by Zopieux** [comment]
Thanks! I adapted your code a bit and used the upstream .deb for Travis. Merged as of [v1.1](/prologin/camisole/releases/tag/v1.1) / f4f6c08.

**Comment by andre2007** [comment]
Great, Thanks a lot!
