### ISSUE TITLE
Vagrant script

### ISSUE THREAD

**Issue by Zopieux** [prologin/camisole#5]
> ###### Originally posted 2016-12-20 13:45 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

**Comment by Zopieux** [comment]
> ###### Originally posted 2017-01-11 20:36 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Mostly done in dbc32eb.

**Comment by seirl** [comment]
> ###### Originally posted 2017-01-13 14:36 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Obsolete?
