### ISSUE TITLE
Docker for camisole

### ISSUE THREAD

**Issue by Kochise** [prologin/camisole#56]
Just for you to know it works (but only in --privileged mode due to cgroup handling, maybe the right --cap-add might do the trick) :

https://github.com/Kochise/docker-camisole

Regards.

https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/services/camisole/-/issues/56
