### ISSUE TITLE
Plugin mode for languages

### ISSUE THREAD

**Issue by seirl** [prologin/camisole#6]
> ###### Originally posted 2017-01-10 18:01 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

We should source python files in paths like:

- `/usr/share/camisole/lang`
- `~/.local/share/camisole/lang`

Maybe split, one file per language?
Configuration file to know which languages we want to enable? `/etc/camisole.conf`? `-c` option?

**Comment by Zopieux** [comment]
> ###### Originally posted 2017-01-13 00:17 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

I've almost finished this, but there is a problem: `$ camisole languages` uses reference files stored in the package. Users can not easily add reference files for their custom languages.

* do we also use *search paths* for ref? seems contrived!
* or do we just embed the ref source in an attribute of each Lang subclass; ugly code-wise, but solves this problem (and also, no need for `MANIFEST.in` when packaging)

**Comment by seirl** [comment]
> ###### Originally posted 2017-01-13 00:20 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

I would say the second one, and we can split the languages in one file per language.

**Comment by Zopieux** [comment]
> ###### Originally posted 2017-01-13 00:22 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Splitting seems like a good idea actually.

**Comment by Zopieux** [comment]
> ###### Originally posted 2017-01-13 21:51 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Add plugin loader system (fix #6)


→ <<cset 6982940b428b>>
