### ISSUE TITLE
Queueing system

### ISSUE THREAD

**Issue by seirl** [prologin/camisole#8]
> ###### Originally posted 2017-01-10 18:15 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

I suggest we use long polling to queue requests, we set a fixed size of concurrent things that can execute in parallel that we can configure (/etc/camisole.conf?) and we add an endpoint to see how many items are queued, what's the average waiting time, etc.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/services/camisole/-/issues/8
