### ISSUE TITLE
Lock mechanism to prevent people from running two instances of Camisole

### ISSUE THREAD

**Issue by seirl** [prologin/camisole#9]
> ###### Originally posted 2017-01-10 18:16 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

This can cause big security issues because of the way we assign UID to the sandboxes.

**Comment by Zopieux** [comment]
> ###### Originally posted 2017-01-13 14:49 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

I guess you'll store the PID in some /var/run/camisole dir? If so, don't forget about [tmpfiles.d](https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html), or maybe you know better ways of packaging this stuff?

**Comment by seirl** [comment]
> ###### Originally posted 2017-03-04 00:52 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Obsoleted by 5d8828c: we're moving towards being stateless and having that info in the filesystem (except for a lock because of some... disputable isolate design choices)
